version: '3.8'
services:
  devcontainer:
    image: devcontainers/jbobos/my_rails6_app:latest
    container_name: my_rails6_app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
