version: '3.8'
services:
  devcontainer:
    image: devcontainers/jcr.jbobos.com/my_rails6_app:latest
    container_name: my_rails6_app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:mariadb
    command: sleep infinity

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=Adelaide123

volumes:
  mariadb-data: